---
title: "Downscale procedure"
author: "Michiel van Dijk"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  word_document:
    reference_docx: ../Common/word_styles_01.docx

---

```{r setup, include=FALSE}
library(rprojroot)
root <- find_root(is_rstudio_project)

library(knitr)
knitr::opts_chunk$set(
  fig.width=12, fig.height=8,
  dpi = 300,
  echo=FALSE, warning=FALSE, message=FALSE,
  fig.path = file.path(root,"FigTabMap/out-"),
  dev = "CairoPNG",
  dev.args = list(CairoPNG = list(bg = "transparent"))
  )

library(pander)
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

#source(file.path(root, "Code/Fig.R"))
#source(file.path(root, "Code/Tab.R"))
```

# STEP X: Downscaling area information to SIMU
before downscaling:
- make sure that cropland >= crop area, if not take land from other agricultural land.
- Find information on fallow land, if so have to create a fallow land coefficient that assumes a share of cropland is fallow
- Find information on cropping intensity (double cropping) and adjust area

On priors:
- Note that a small prior results in the allocation of very small shares of crop land, which is not desirable.
- better to cut of priors arguing that if yield or transport costs are < X they are set to zero.

Solving model
- Check if there are infeasability issues with solving - will be clear in LOG

Dealing with different systems (intensification as in SPAM)
- Either just allocate crops without making any assumptions on the system. This means that in fact the systems distribution that are in GLOBIOM are used in the end. This takes area from the downscaling, production from FAOSTAT and relative yields per system from EPIC. All yields are scaled so that production FAOSTAT/area downscaling = yield.
- Already incorporate information on irrigated areas in the downscaling and use SPAM to distribute the three rainfed systems => this will replace the distribution of systems from SPAM.


Postprocessing:
- If crop area < cropcover, excess cropland needs to be distributed to other natural land as cropland needs to be equal to crop cover in GLOBIOM.
- Other option is to assume that excess crop cover is allocated to a crop that is not in the system and is therefore fixed (not recommended)

Livestock
- Check livestock map by ILRI and compare with land cover. Probably no need to adjust.
- 

# To DO
- Use rural population instead of total population for priors => use rural mask from SPAM
- Assess what determines location of production: only population or also distance, profitability etc.





QUESTIONS LIANG
Aim is to be able to create land use maps using SPAM but with flexibility to add data from stakeholders and for multiple years. 
- Multiple years
- Try to validate maps with LSMS-ISA data => case study data
- Try to allocate livestock to grassland.


Questions:
- How to deal with missing data. Understand that if one only has adm1 data, eq 12 holds only for adm1 for that crop. 
- But what about if there is no data at all for a crop at adm1 level? For instance data for MWI at adm1 (from CountryStat) only covers a few crops. Not banana. Banana is mapped in SPAM in MWI, probably from FAOSTAT. How?
- How to deal with subnational cropstatistics that only cover core crops. Downscale other crops from national level downwards?

- How to deal with border issues => center rule? Some cells are partly outside the country!

Next steps
- co-author on paper, perhaps using new techniques with case study for one country?


Questions on downscaling
- What is scalelp? Something is scaled with exogenous variable. Why? Related to alloc.up(i,j) = min(scalelp,scalelp*pixel*avail(i)/produ(j))$produ(j);
- Why is suitability turned into a bound (not an equation)?
- what is deptot (ratio per main crop)? From eq 12 (subcrop), it should be total area of crop j in adm k but description says 'ratio' 

- Why the name production of crops? This is in fact total physical area for crop j, right. 
- When subnational data is available, slack is minimized not entropy....
- How to deal when harvested area is larger than land cover in some ADMs.
- How to deal with countries where not all adm2 are covered?
- CHECK: is outcome of SPAM physical area or harvested area? In first case, how is it linked with FAOSTAT harvested area?
- How to determine irrigated area per crop (one of the four systems)? Is there data on irrigated area per crop?




ANSWERS LIANG
-	So far I have not been able to add the suitability maps because I do not have them. Downloading the maps one by one from the GAEZ is very cumbersome so I contacted Gunther Fischer directly. Although he promised to share them, this has not happened and he is very difficult to contact. Would it be possible for me to download them from an IFPRI server?

-	I also wonder why you use the suitability maps as hard constraints in the model. I would argue that it makes more sense to use the suitability maps to inform the prior. Perhaps we can discuss.

-	How do you deal with grid cells on the borders of countries? When I rasterize the Malawi polygon to 5 arcmin there are obviously borders which are not covered (those where the center of the raster cell is outside the country). One possibility is to take a different rasterize approach and calculate the share of the border cell that is located in Malawi (<50%) and allocate land cover to them. More work and I am not sure if it is worth to invest in it. 

-	My land cover map presents physical value areas for crops that are around 20% larger than total harvested area from FAOSTAT. At the moment I left it this way and let the model decide where to allocate. As a consequence some land cover cells are not allocated any harvested area but also crops, such as maize, might have a ‘ thin’ distribution. On p. 24 of the manual, I read that you constrain the land cover are to the physical area statistical value even before you run the model (by sorting the land cover data using  the ‘reliability factor’). Why do you not let the model decide, like I do?


Then some general questions about your GAMS code and my results:
-	You use a scaling factor (scalelp) in all equations. Where does this come from? On p. 20 of the technical documentation the gamma scaling parameter is described but I don’t think this is the same thing – or I simply do not understand. => SOLVED

-	It seems that your preferred model for countries with subnational data is landfeas, which minimizes the slack values. So far I have used the entropy model (landentsn), which solves (locally optimal) but, indeed, gives very large (and unrealistically) high slack values for a number of grid cells. Hope you can advise on this point. 

-	Some marginal issues. Deptot is the ratio per main crop?. “ratio” is a bit odd here for me. It is total area of crop j in adm k but description, right? Similar for produ(j) which is described as production of crops but this is total physical area for crop j, right?

# PROGRESS SPAM AND WHICH VERSION FOR 2005 => DATAVERSE


# Think about
- how to deal with multicropping and conversion to area harvested if we would have such data
- how to deal with fallowing
- how to flexibly add new crops, e.g. palm oil. => not difficult because we already consider 40 crops, incl oil palm
  