---
title: "Global-to-local GLOBIOM procedure"
author: "Michiel van Dijk"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  word_document:
    reference_docx: ../Common/word_styles_01.docx
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
GLOBIOM has been designed as global asssessment tool. Most input data is defined at the [0.5 degree] spatial level. Recently, there has been increasing demand for regional and subnational assessments that focus an a specific geographical region. Examples are land use change studies for Brazil, Congo, Ethiopia and Indonesia and an assessment of the water-land-energy nexus in the Zambezi and Indus river basins.The global datasets that are normally used for assessments are too coarse to arrive at the level of detail that is demanded for this type of studies and therefore needs to be replaced more detailed information that have a higher spatial resolution, if available.  

This document describes the various steps to prepare GLOBIOM for regional or subnational assessments. Refining the land use and land cover data for subnational assessments can be very time and resource-demanding and demands a certain craftsmanship. It is recommended to only follow the full process for relative large projects that take at least around two years. It is also advisable to involve local partners and stakeholders to provide input data (e.g. land use maps and production statistics) and validate processed information (e.g. updated land use map that is used in GLOBIOM) 
 

# Data processing pipeline
Figure X shows a flowchart for all the steps to prepare the data. We will discuss them one by one. 

## Collect additional data
Preferably the following information should be updated in GLOBIOM:
- Area and production for each product (see Annex) by administrative unit in 2000 (and 2010)
- Land cover map classes by simulation unit for 2000 and (2010) [@Are there standard classes?]
- Protected areas map.
- Costs. At the moment only fertilizer and irrigation costs. Additional household data might improve the present information that is used in GLOBIOM, which is provided at a very high level (national/regional.)
- Productivity [?]

It highly depends on the region, which data is available and at which level. We recommend to take a pragmatic approach, using data from household surveys (e.g. LSMS-ISA, LSMS, etc), national statistics and specialised ministries and institutes. The following sections describe some rules of thumb that can be used to update the information.

## Area and production.
National statistics and household surveys provide the best information for detailed information on agricultural production. In most cases it should be possible to collect information on total production, crop area and/or harvested area at the second administrative level (e.g. province). Sometimes it will be necessary to add additional crops that are not part of the standard GLOBIOM crop classification (e.g. teff in Ethiopia) 

When production data is not available, another approach can be to collect information on average consumption or diets and combine this with population density maps to approximate total consumption at the level of the administrative unit. As in many poor countries, the agricultural sector is characterised by subsistince farming, consumption is a reasonable proxy for production in case no other information is available.

## Land cover map
Many countries publish detailed land cover maps, that provide information on the location of crop land, forest land, agro-industrial plantation (consessions), timeber plantations (concesstions), forest land, urbanised land and unused areas (i.e. rock). These maps can be used to improve the land cover map in GLOBIOM at the simulation unit level. 

## Harmonise data 
- Ensure to harmonise the administrative boundaries over time. In many countries they tend to change over time. 
- Compare data from different sources and over time.

## Downscale land use and production data
Code in GAMS is provided to downscale and harmonise the land use and land cover data to the GLOBIOM simu levels. Downscaling is performed using priors that provide information on the suitability of certain crops or transportation costs. Downscaling is mostly down for crops as only limited information tends to be available on livestock. It is a separate optimization problem for each of the administrative units for which detailed production data is collected and can therefore be treated as a large number of parallel processes. 


# GLOBIOM set up

# Regional module
- Creates one GDX file with all information for the region you are studying. 
- Add some lines in the aggregation phase, where regional data is replaced by new updated information.

## Folder structure
Add a country case study folder in GAMS that will be used for all (sub)national statistics. It will have the same structure as a standard global data folder in GLOBIOM.

## Trade
Have to decide if you would keep one region or split countries. In latter case, adopt regional trade block and model trade with total block not bilaterally.
 
## Consumption


- 
