---
title: "Global-to-local GLOBIOM procedure"
author: "Michiel van Dijk"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  word_document:
    reference_docx: ../Common/word_styles_01.docx
bibliography: ../Common/micro-GLOBIOM.bib
    
---

```{r setup, include=FALSE}
library(rprojroot)
root <- find_root(is_rstudio_project)

library(knitr)
knitr::opts_chunk$set(
  fig.width=12, fig.height=8,
  dpi = 300,
  echo=FALSE, warning=FALSE, message=FALSE,
  fig.path = file.path(root,"FigTabMap/out-"),
  dev = "CairoPNG",
  dev.args = list(CairoPNG = list(bg = "transparent"))
  )

library(pander)
panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

source(file.path(root, "Code/Fig.R"))
source(file.path(root, "Code/Tab.R"))
source(file.path(root, "Code/Map.R"))
```

# Introduction

```{r Table-1}

```

```{r Figure-1}

```



# References